name: Deploy iFlow to SAP CPI Tenant

on:
  push:
    branches:
      - main

jobs:
  deploy-to-cpi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Step 1 - Fetch OAuth Bearer Token from BTP
        id: get_token
        run: |
          RESPONSE=$(curl -s -X POST "https://2b66bf74trial.authentication.us10.hana.ondemand.com/oauth/token" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "grant_type=client_credentials" \
            -d "client_id=sb-c6c0a74f-572b-452d-9a4b-88e0b7890972!b703443|it-rt-2b66bf74trial!b55215" \
            -d "client_secret=ef921040-aaff-4a36-bc67-a6faff89cba9$VaqyVpb6Br4xbCtdmTrp-wCe9sZL6BhAPt10c58erks=")
          
          TOKEN=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.load(sys.stdin).get('access_token', ''))")
          
          if [ -z "$TOKEN" ] || [ "$TOKEN" == "None" ]; then
            echo "Error: OAuth Authentication Failed. Full BTP Response:"
            echo "$RESPONSE"
            exit 1
          fi

          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Step 2 - Trigger iFlow Runtime Deployment via REST API
        run: |
          curl -k -i -X POST "${{ secrets.BTP_CPI_API_URL }}/api/v1/DeployIntegrationDesigntimeArtifact?Id='Inbound_Security_Gateway'&Version='active'" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Length: 0"